### ISSUE TITLE
hello world无法输出核函数内部的打印信息

### ISSUE THREAD

**Issue by GeneralJing** [Tony-Tan/CUDA_Freshman#7]
下载完代码，编译后，执行hello_world核函数内部的日志未输出，
cudaDeviceReset();//if no this line ,it can not output hello world from gpu
  cudaDeviceSynchronize();
添加这两个都不起作用。

**Comment by GeneralJing** [comment]
还有别的设置需要更改吗？

**Comment by Tony-Tan** [comment]
> 

what's your device and cuda version?

**Comment by GeneralJing** [comment]
solved. change the cuda version from 11.0 to 10.0, it can print.

**Comment by Hukongtao** [comment]
> 下载完代码，编译后，执行hello_world核函数内部的日志未输出， cudaDeviceReset();//if no this line ,it can not output hello world from gpu cudaDeviceSynchronize(); 添加这两个都不起作用。

小白问下，怎么编译啊
