### ISSUE TITLE
博客打不开了。

### ISSUE THREAD

**Issue by renhaofan** [Tony-Tan/CUDA_Freshman#9]
貌似因为你更新了个人主页的原因。  We're having a really bad day.

The Unicorns have taken over. We're doing our best to get them under control and get GitHub back up and running.

**Comment by Tony-Tan** [comment]
> 貌似因为你更新了个人主页的原因。 We're having a really bad day.
> 
> The Unicorns have taken over. We're doing our best to get them under control and get GitHub back up and running.

I had just updated a new website but they are totally two different repos. If you are visiting from China mainland that may be the problem of network. Please try again later and let me know what is going on

**Comment by renhaofan** [comment]
> > 貌似因为你更新了个人主页的原因。 We're having a really bad day.
> > The Unicorns have taken over. We're doing our best to get them under control and get GitHub back up and running.
> 
> I had just updated a new website but they are totally two different repos. If you are visiting from China mainland that may be the problem of network. Please try again later and let me know what is going on

Thanks. Your blog is accessible successfully now.
